[package]
name = "citrus327_my_crate"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "my first rust crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[registry]
default = "crates-io"
